accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)        # settings를 통해서 직접 가져온다

    class Meta:
        ordering = ('-pk', )




class Comment(models.Model):
    article = models.ForeignKey(Article, related_name='comments', on_delete=models.CASCADE)         # related_name --> 아티클은 comment를 뭐라고 부를건지 지정해주는거
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-pk', )

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model  # 현재 활성화(active)된 user model을 return 한다

class CustomUserChangeForm(UserChangeForm):
    
    class Meta:
        model = get_user_model()
        fields = ['email', 'first_name', 'last_name',]

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ['title', 'content', ]


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content', ]
        # exclude = ['article', ]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login, logout as auth_logout, update_session_auth_hash  # 겹치니깐 이렇게 임포트
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from . forms import CustomUserChangeForm

# Create your views here.

def signup(request):
    if request.method == 'POST':
        # 회원가입로직
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect('articles:index')
    else:   # == 'GET'
        form = UserCreationForm()
    context = { 'form': form }
    return render(request, 'accounts/form.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == 'POST':
        # 로그인로직
        form = AuthenticationForm(request, request.POST)    # 이거 시험
        if form.is_valid():
            auth_login(request, form.get_user())
            next_page = request.GET.get('next')
            return redirect(next_page or 'articles:index')
    else: # == 'GET'
        form = AuthenticationForm()    
        
    context = { 'form': form }
    return render(request, 'accounts/form.html', context)

def logout(request):
    auth_logout(request)
    return redirect('articles:index')

@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
    return redirect('articles:index')

def update(request):
    if request.method == 'POST':
        # 수정해주세요 요청이 들어올때
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('article:index')
    else: # GET요청이 들어옴
        # 수정할 수 있는 페이지 주세요 요청이 들어올때
        form = CustomUserChangeForm(instance=request.user)
    context = { 'form': form }
    return render(request, 'accounts/form.html', context)

@login_required
def password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, user)
            return redirect('accounts:update')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form': form}
    return render(request, 'accounts/form.html',context)

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_GET
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from IPython import embed


@require_GET
def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)


@require_GET
def detail(request, article_pk):
    # 사용자가 url 에 적어보낸 article_pk 를 통해 디테일 페이지를 보여준다.
    article = get_object_or_404(Article, pk=article_pk)
    comment_form = CommentForm()
    comments = article.comments.all()           # related_name 지정해줘서 이렇게 써도됨
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'articles/detail.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        # Article 을 생성해달라고 하는 요청
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else: # GET
        # Article 을 생성하기 위한 페이지를 달라고 하는 요청
        form = ArticleForm()
    context = {'form': form}
    return render(request, 'articles/create.html', context)

@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if article.user == request.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article_pk)
        else: # GET method
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')
    context = {'form': form}
    return render(request, 'articles/update.html', context)


@require_POST
def delete(request, article_pk):
    if request.user.is_authenticated:
        # article_pk 에 맞는 article 을 꺼낸다. 삭제한다.
        article = get_object_or_404(Article, pk=article_pk)
        if article.user == request.user:
            article.delete()
        else:
            return redirect('articles:detail', article_pk)
    return redirect('articles:index')
    


# 댓글을 생성하는 요청을 받는다.
@require_POST
def comments_create(request, article_pk):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.article_id = article_pk
        comment.user = request.user
        comment.save()
    return redirect('articles:detail', article_pk)


@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if comment.user == request.user:
            comment.delete()
            return redirect('articles:detail', article_pk)
        else:
            return redirect('articles:detail', article_pk)
    else:
        return HttpResponse('You are Unauthorized', status=401)

accounts/templates/accounts/form.html
{% extends 'base.html' %}

{% block title %}Accounts{% endblock title %}

{% block container %}

{% if request.resolver_math.url_name == 'signup' %}
<h2>회원가입</h2>
{% elif request.resolver_math.url_name == 'login' %}
<h2>로그인</h2>
{% elif request.resolver_math.url_name == 'update '%}
<h2>내정보수정</h2>
{% else %}
<h2>비밀번호 변경</h2>
{% endif %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>
{% endblock container %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Accounts::로그인{% endblock title %}

{% block container %}
<h2>로그인</h2>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="sumbit">로그인하기</button>
</form>
{% endblock container %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
​
{% block title %}Accounts::비밀번호 변경{% endblock title %}
​
{% block container %}
  <h2>비밀번호 변경</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-danger", type="submit">비밀번호 변경</button>
  </form>
{% endblock container %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}Accounts::회원가입{% endblock title %}

{% block container %}
<h2>회원가입</h2>
{% comment %}  같은곳으로 보낼거면 액션 생략 {% endcomment %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p}}
  <button type="submit">회원가입</button>
</form> 
{% endblock container %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block title %}Accounts::수정{% endblock title %}

{% block container %}
<h2>내 정보 수정</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p}}
  <button type="submit">수정하기</button>
</form>
{% endblock container %}

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}Article::Create{% endblock title %}

{% block container %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">생성하기</button>
</form>
{% endblock container %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}Article::Detail{% endblock title %}

{% block container %}
<h2>{{ article.title }}</h2>
<p>{{ article.created_at }}</p>
<p>작성자 : {{ article.user }}</p>
<hr>
<p>{{ article.content }}</p>
<hr>
{% if user.is_authenticated %}
  {% if article.user == request.user %}
    <a href="{% url 'articles:update' article.pk %}">[수정하기]</a>
    <form action="{% url 'articles:delete' article.pk %}" method="post">
      {% csrf_token %}
      <button type="submit">삭제하기</button>
    </form>
  {% endif %}
{% else %}
    <a href=" {% url 'accounts:login' %} ">수정/삭제하려면 로그인하세요</a>
{% endif %}


<hr>
<h3>Comments</h3>
<form action="{% url 'articles:comments_create' article.pk %}" method="post">
  {% csrf_token %}
  {{ comment_form.as_table }}
  {% if user.is_authenticated %}
    <button type="submit">작성하기</button>
  {% else %}
    <a href=" {% url 'accounts:login' %}">작성하려면 로그인</a>
  {% endif %}
</form>
<hr>
<ul>
{% for comment in comments %}
  <li>
    <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="post">
      {% csrf_token %}
      <span>{{ comment.content }} - {{ comment.created_at }}</span>
      <p>작성자 : {{ comment.user }}</p>
      {% if user.is_authenticated %}
        {% if comment.user == request.user %}
          <button type="submit">삭제하기</button>
        {% endif %}
      {% else %}
        <a href=" {% url 'accounts:login' %}">삭제하려면 로그인</a>
      {% endif %}
    </form>
  </li>
{% endfor %}
</ul>

{% endblock container %}

articles/templates/articles/index.html
{% extends 'base.html' %}


{% block title %}Article::Index{% endblock title %}

{% block container %}
<h2>Article List</h2>
{% if user.is_authenticated %}
  <a href="{% url 'articles:create' %}">[생성하기]</a>

{% else %}
<p><a href=" {% url 'accounts:signup' %}">게시글을 작성하기 위해 회원이 되어보세요</a></p>
{% endif %}
<hr>
{% for article in articles %}
<div>
  <h3>{{ article.pk }}. {{ article.title }}</h3>
  <p>작성자 : {{ article.user }}</p>
  <a href="{% url 'articles:detail' article.pk %}">[상세보기]</a>
</div>
<br>
{% endfor %}

{% endblock container %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block title %}Article::Update{% endblock title %}

{% block container %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">수정하기</button>
</form>
{% endblock container %}

review/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <meta http-equiv="X-UA-Compatible" content="ie=edge">
 <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-reboot.min.css' %}">
 <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-grid.min.css' %}">
 <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
 <title>{% block title %}{% endblock title %}</title>
</head>
<body>
 <header>
   <h1>저희 페이지 오신걸 환영합니다.</h1>
   {% if user.is_authenticated %}
   <p>
     <span> Hello, {{ user.username }} </span>
     <a href="{% url 'accounts:logout' %}">[로그아웃]</a>
     <a href=" {% url 'accounts:update' %}">[회원정보 수정]</a>
     <form action="{% url 'accounts:delete' %}" method='post'>
       {% csrf_token %}
       <button type="submit">회원탈퇴</button>
     </form>
   </p>
   {% else %}
   <p>
     <a href="{% url 'accounts:signup' %}">회원가입</a>
     <a href="{% url 'accounts:login' %}">로그인</a>
   </p>
   {% endif %}
   <a href="{% url 'articles:index' %}">[목록]</a>
   <hr>
 </header>
 {% block container %}{% endblock container %}
 <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>